image:
  file: .gitpod.Dockerfile

tasks:
  - name: setup
    init: |
      poetry install
      npm install
    command: |
      poetry run invoke init-workspace --type gitpod

ports:
  - port: 8000
    onOpen: notify
  - port: 6501-6502
    onOpen: ignore
  - port: 7501-7502
    onOpen: ignore
  - port: 11122
    onOpen: ignore
  - port: 5678
    onOpen: ignore

vscode:
  extensions:
    - "batisteo.vscode-django"
    - "charliermarsh.ruff"
    - "davidanson.vscode-markdownlint"
    - "eamodio.gitlens"
    - "esbenp.prettier-vscode"
    - "formulahendry.auto-rename-tag"
    - "foxundermoon.shell-format"
    - "grapecity.gc-excelviewer"
    - "mhutchie.git-graph"
    - "mikestead.dotenv"
    - "monosans.djlint"
    - "ms-azuretools.vscode-docker"
    - "ms-pyright.pyright" # Replaces pylance as it is not available in Open VSX
    - "ms-python.black-formatter"
    - "ms-python.python"
    - "streetsidesoftware.code-spell-checker"
    - "tamasfe.even-better-toml"
    - "wayou.vscode-todo-highlight"
