image:
  file: .gitpod.Dockerfile

tasks:
  - name: setup
    init: |
      mkdir -p /workspace/.pip-modules/bin
      ln -s /home/gitpod/.local/share/pypoetry/venv/bin/poetry /workspace/.pip-modules/bin/poetry
      poetry install
      npm install
    command: |
      ./scripts/init_gitpod.sh
      ./scripts/adit_dev_up.sh

ports:
  - port: 8000
    onOpen: notify
  - port: 6501-6502
    onOpen: ignore
  - port: 7501-7502
    onOpen: ignore
  - port: 11122
    onOpen: ignore
  - port: 5678
    onOpen: ignore

vscode:
  extensions:
    # Python / Django stuff
    - "batisteo.vscode-django"
    - "charliermarsh.ruff"
    - "davidanson.vscode-markdownlint"
    - "eamodio.gitlens"
    - "esbenp.prettier-vscode"
    - "formulahendry.auto-rename-tag"
    - "foxundermoon.shell-format"
    - "mhutchie.git-graph"
    - "mikestead.dotenv"
    - "monosans.djlint"
    - "ms-azuretools.vscode-docker"
    - "ms-python.python"
    - "streetsidesoftware.code-spell-checker"
    - "wayou.vscode-todo-highlight"
    # C++ stuff
    - bbenoist.doxygen
    - cheshirekow.cmake-format
    - llvm-vs-code-extensions.vscode-clangd
    - ms-vscode.cmake-tools
    - ms-vscode.makefile-tools
    - twxs.cmake
    - webfreak.debug
