x-app: &default-app
  volumes:
    - web_data:/var/www/web
    - ${BACKUP_DIR:?}:/backups
    - ${MOUNT_DIR:?}:/mnt
  depends_on:
    - postgres
  environment:
    ADIT_AE_TITLE: ${ADIT_AE_TITLE:?}
    BACKUP_DIR: ${BACKUP_DIR:?}
    DATABASE_URL: "psql://postgres:postgres@postgres.local:5432/postgres"
    DJANGO_ADMIN_EMAIL: ${DJANGO_ADMIN_EMAIL:?}
    DJANGO_ADMIN_FULL_NAME: ${DJANGO_ADMIN_FULL_NAME:?}
    DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:?}
    DJANGO_CSRF_TRUSTED_ORIGINS: ${DJANGO_CSRF_TRUSTED_ORIGINS:?}
    DJANGO_INTERNAL_IPS: ${DJANGO_INTERNAL_IPS:?}
    DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:?}
    DJANGO_SERVER_EMAIL: ${DJANGO_SERVER_EMAIL:?}
    DJANGO_STATIC_ROOT: "/var/www/web/static/"
    FILE_TRANSMIT_HOST: "receiver.local"
    FILE_TRANSMIT_PORT: 14638
    HTTP_PROXY: ${HTTP_PROXY:-}
    HTTPS_PROXY: ${HTTPS_PROXY:-}
    MOUNT_DIR: ${MOUNT_DIR:?}
    NO_PROXY: ${NO_PROXY:-}
    ORTHANC1_DICOM_PORT: 7501
    ORTHANC1_DICOMWEB_ROOT: "dicom-web"
    ORTHANC1_HOST: "orthanc1.local"
    ORTHANC1_HTTP_PORT: 6501
    ORTHANC2_DICOM_PORT: 7502
    ORTHANC2_DICOMWEB_ROOT: "dicom-web"
    ORTHANC2_HOST: "orthanc2.local"
    ORTHANC2_HTTP_PORT: 6502
    PROJECT_VERSION: ${PROJECT_VERSION:-vX.Y.Z}
    RECEIVER_AE_TITLE: ${RECEIVER_AE_TITLE:?}
    SITE_DOMAIN: ${SITE_DOMAIN:?}
    SITE_NAME: ${SITE_NAME:?}
    SITE_USES_HTTPS: ${SITE_USES_HTTPS:-false}
    STORE_SCP_HOST: "receiver.local"
    STORE_SCP_PORT: 11112
    SUPERUSER_AUTH_TOKEN: ${SUPERUSER_AUTH_TOKEN:-}
    SUPERUSER_EMAIL: ${SUPERUSER_EMAIL:-}
    SUPERUSER_USERNAME: ${SUPERUSER_USERNAME:-}
    SUPERUSER_PASSWORD: ${SUPERUSER_PASSWORD:-}
    SUPPORT_EMAIL: ${SUPPORT_EMAIL:?}
    TOKEN_AUTHENTICATION_SALT: ${TOKEN_AUTHENTICATION_SALT:?}
    USE_DOCKER: "true"
    USER_TIME_ZONE: ${USER_TIME_ZONE:?}

services:
  init:
    <<: *default-app
    hostname: init.local

  web:
    <<: *default-app
    hostname: web.local

  postgres:
    image: postgres:17
    hostname: postgres.local
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dicom_worker:
    <<: *default-app
    hostname: dicom_worker.local

  default_worker:
    <<: *default-app
    hostname: default_worker.local

  receiver:
    <<: *default-app
    hostname: receiver.local

  orthanc1:
    image: jodogne/orthanc-plugins:1.12.4
    hostname: orthanc1.local
    configs:
      - source: orthanc1_config
        target: /etc/orthanc/orthanc.json
    volumes:
      - orthanc1_data:/var/lib/orthanc/db

  orthanc2:
    image: jodogne/orthanc-plugins:1.12.4
    hostname: orthanc2.local
    configs:
      - source: orthanc2_config
        target: /etc/orthanc/orthanc.json
    volumes:
      - orthanc2_data:/var/lib/orthanc/db

configs:
  orthanc1_config:
    file: ./orthanc/orthanc1.json
  orthanc2_config:
    file: ./orthanc/orthanc2.json

volumes:
  web_data:
  postgres_data:
  orthanc1_data:
  orthanc2_data:
