[tool.poetry]
name = "adit"
version = "0.23.3"
description = "ADIT (Automated DICOM Transfer) is a swiss army knife to exchange DICOM data between various systems by using a convenient web frontend."
authors = ["medihack <kai.schlamp@gmail.com>"]
license = "GPLv3"

[tool.poetry.dependencies]
cchardet = "^2.1.7"
celery = "^5.2.7"
channels = "^4.0.0"
channels-redis = "^4.0.0"
crispy-bootstrap4 = "^2022.1"
cryptography = "^40.0.1"
daphne = "^4.0.0"
dicognito = "^0.15.0"
Django = "^4.0.6"
django-crispy-forms = "^2.0"
django-environ = "^0.10.0"
django-extensions = "^3.1.5"
django-filter = "^23.1"
django-htmx = "^1.14.0"
django-loginas = "^0.3.9"
django-registration-redux = "^2.10"
django-revproxy = { git = "https://github.com/jazzband/django-revproxy.git" }
django-tables2 = "^2.3.3"
djangorestframework = "^3.13.1"
flower = "^1.0.0"
humanize = "^4.0.0"
Markdown = "^3.3.7"
pika = "^1.1.0"
psycopg2 = "^2.9.3"
pydicom = "^2.3.0"
pynetdicom = "^2.0.2"
python = "^3.9"
redis = "^4.3.4"
toml = "^0.10.2"
Twisted = { extras = ["tls", "http2"], version = "^22.2.0" }
whitenoise = "^6.0.0"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
celery-types = "^0.15.0"
debugpy = "^1.6.2"
django-debug-permissions = "^1.0.0"
django-debug-toolbar = "^3.2.4"
django-types = "^0.17.0"
djlint = "^1.19.16"
factory-boy = "^3.1.0"
Faker = "^18.3.1"
ipykernel = "^6.17.1"
ipython = "^8.1.1"
pyright = "^1.1.264"
pytest = "^7.1.2"
pytest-asyncio = "^0.21.0"
pytest-celery = "^0.0.0"
pytest-cov = "^4.0.0"
pytest-django = "^4.5.2"
pytest-picked = "^0.4.4"
pytest-playwright = "^0.3.0"
pytest-watch = "^4.2.0"
requests = "^2.27.1"
ruff = "^0.0.260"
time-machine = "^2.1.0"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "adit.settings.development"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
testpaths = "adit"
log_cli = 0
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
markers = ["integration: mark a test as an integration test."]
filterwarnings = [
    "ignore:SelectableGroups dict interface is deprecated:DeprecationWarning",
    "ignore:The USE_L10N setting is deprecated:django.utils.deprecation.RemovedInDjango50Warning",
]

[tool.ruff]
exclude = ["migrations"]
line-length = 100
select = ["E", "F", "I", "DJ"]

[tool.black]
exclude = "migrations"
line-length = 100

[tool.djlint]
profile = "django"
max_line_length = 120
ignore = "T002"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
