[tool.poetry]
name = "adit"
version = "0.33.1"
description = "ADIT (Automated DICOM Transfer) is a swiss army knife to exchange DICOM data between various systems by using a convenient web frontend."
authors = ["medihack <kai.schlamp@gmail.com>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
adit-radis-shared = {git = "https://github.com/openradx/adit-radis-shared.git", rev = "v0.6.2"}
adrf = "^0.1.1"
aiofiles = "^24.1.0"
asyncinotify = "^4.0.1"
channels = "^4.0.0"
crispy-bootstrap5 = "^2024.2"
cryptography = "^42.0.5"
daphne = "^4.0.0"
dicognito = "^0.17.0"
dicomweb-client = "^0.59.1"
Django = "^5.0.4"
django-crispy-forms = "^2.0"
django-dbbackup = "^4.0.2"
django-environ = "^0.11.2"
django-extensions = "^3.1.5"
django-filter = "^24.2"
django-htmx = "^1.14.0"
django-loginas = "^0.3.9"
django-pglock = "^1.5.1"
django-registration-redux = "^2.10"
django-revproxy = { git = "https://github.com/jazzband/django-revproxy.git" }
django-tables2 = "^2.3.3"
djangorestframework = "^3.13.1"
humanize = "^4.0.0"
janus = "^1.0.0"
Markdown = "^3.3.7"
openpyxl = "^3.1.2"
pandas = "^2.0.1"
pebble = "^5.0.3"
procrastinate = { extras = ["django"], version = "^2.8.0" }
psycopg = { extras = ["binary"], version = "^3.1.12" }
pyarrow = "^16.1.0"
pydicom = "^2.3.0"
pynetdicom = "^2.0.2"
python = ">=3.11,<4.0"
toml = "^0.10.2"
Twisted = { extras = ["tls", "http2"], version = "^24.3.0" }
wait-for-it = "^2.2.2"
watchfiles = "^0.22.0"
whitenoise = "^6.0.0"

[tool.poetry.group.dev.dependencies]
debugpy = "^1.6.2"
django-browser-reload = "^1.11.0"
django-debug-permissions = "^1.0.0"
django-debug-toolbar = "^4.1.0"
django-test-migrations = "^1.3.0"
django-types = "^0.19.1"
djangorestframework-types = "^0.8.0"
djlint = "^1.19.16"
factory-boy = "^3.1.0"
Faker = "^26.0.0"
invoke = "^2.1.2"
ipykernel = "^6.17.1"
ipython = "^8.1.1"
nest-asyncio = "^1.5.6"
pyright = "^1.1.351"
pytest = "^8.1.1"
pytest-asyncio = "^0.23.6"
pytest-cov = "^5.0.0"
pytest-django = "^4.5.2"
pytest-mock = "^3.10.0"
pytest-only = "^2.0.0"
pytest-picked = "^0.5.0"
pytest-playwright = "^0.5.0"
pytest-timeout = "^2.1.0"
pytest-watch = "^4.2.0"
python-dotenv = "^1.0.0"
pywatchman = "^2.0.0"
requests = "^2.27.1"
ruff = "^0.5.1"
time-machine = "^2.1.0"
vermin = "^1.5.2"

[tool.pyright]
ignore = ["**/migrations", "**/*.ipynb"]
typeCheckingMode = "basic"
reportUnnecessaryTypeIgnoreComment = true
reportWildcardImportFromLibrary = false

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "adit.settings.development"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
testpaths = ["adit"]
log_cli = 0
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
markers = ["integration: mark a test as an integration test."]
filterwarnings = [
    # We already fixed this, so we only need to remove this ignore with next major version of factory boy
    "ignore:.*Factory._after_postgeneration will stop saving the instance:DeprecationWarning",
    "ignore:'cgi' is deprecated:DeprecationWarning",
    'ignore:.*use of fork\(\) may lead to deadlocks.*:DeprecationWarning',
    'ignore:.*Use timezone-aware objects to represent datetimes in UTC.*:DeprecationWarning',
]
timeout = 60

[tool.coverage.run]
branch = true
source = ["adit"]

[tool.coverage.report]
skip_empty = true
show_missing = true

[tool.ruff]
exclude = ["migrations"]
line-length = 100
lint.select = ["E", "F", "I", "DJ"]

[tool.djlint]
profile = "django"
max_line_length = 120
ignore = "H021,H030,H031,T002"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
