version: "3.8"

x-app: &default-app
  volumes:
    - /mnt:/mnt
  depends_on:
    - postgres
    - rabbit
    - redis
  environment:
    USE_DOCKER: 1
    DATABASE_URL: "psql://postgres:postgres@postgres:5432/postgres"
    RABBITMQ_URL: "amqp://rabbit"
    REDIS_URL: "redis://redis:6379/0"
    DJANGO_STATIC_ROOT: "/var/www/adit/static/"
    RABBIT_MANAGEMENT_HOST: "rabbit"
    RABBIT_MANAGEMENT_PORT: "15672"
    FLOWER_HOST: "flower"
    FLOWER_PORT: "5555"
    ORTHANC1_HOST: "orthanc1"
    ORTHANC1_HTTP_PORT: 6501
    ORTHANC1_DICOM_PORT: 7501
    ORTHANC1_DICOMWEB_ROOT: "dicom-web"
    ORTHANC2_HOST: "orthanc2"
    ORTHANC2_HTTP_PORT: 6502
    ORTHANC2_DICOM_PORT: 7502
    ORTHANC2_DICOMWEB_ROOT: "dicom-web"
    FILE_TRANSMIT_HOST: "receiver"
    FILE_TRANSMIT_PORT: 14638
    STORE_SCP_HOST: "receiver"
    STORE_SCP_PORT: 11112

services:
  web:
    <<: *default-app
    build:
      context: ..
    volumes:
      # Cave, overwrites the above anchor
      - /mnt:/mnt
      - adit_data:/var/www/adit

  postgres:
    image: postgres:13.12
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dicom_worker:
    <<: *default-app

  celery_worker:
    <<: *default-app

  celery_beat:
    <<: *default-app

  receiver:
    <<: *default-app

  flower:
    <<: *default-app
    expose:
      - "5555"
    command: >
      bash -c "
        wait-for-it -s rabbit:5672 -t 60 &&
        celery --broker=amqp://rabbit/ flower --url_prefix=flower
      "

  # RabbitMQ authentication can't be disabled. So when we try to log into
  # the management console we have to use "guest" as username and password.
  # The real authentication happens by ADIT itself, because the management
  # console is behind a ProxyView.
  rabbit:
    image: rabbitmq:3.12.2-management
    expose:
      - "5672"
      - "15672"
    configs:
      - source: rabbit_config
        target: /etc/rabbitmq/rabbitmq.conf
    volumes:
      - rabbit_data:/var/lib/rabbitmq

  redis:
    image: redis:7.2.3
    expose:
      - "6379"
    volumes:
      - redis_data:/data

  orthanc1:
    image: jodogne/orthanc-plugins:1.12.1
    expose:
      - "6501"
      - "7501"
    configs:
      - source: orthanc1_config
        target: /etc/orthanc/orthanc.json
    volumes:
      - orthanc1_data:/var/lib/orthanc/db

  orthanc2:
    image: jodogne/orthanc-plugins:1.12.1
    expose:
      - "6502"
      - "7502"
    configs:
      - source: orthanc2_config
        target: /etc/orthanc/orthanc.json
    volumes:
      - orthanc2_data:/var/lib/orthanc/db

configs:
  rabbit_config:
    file: ./rabbitmq/rabbitmq.conf
  orthanc1_config:
    file: ./orthanc/orthanc1.json
  orthanc2_config:
    file: ./orthanc/orthanc2.json

volumes:
  adit_data:
  postgres_data:
  rabbit_data:
  redis_data:
  flower_data:
  orthanc1_data:
  orthanc2_data:
