x-app: &default-app
  volumes:
    - /mnt:/mnt
  depends_on:
    - postgres
  environment:
    USE_DOCKER: 1
    DATABASE_URL: "psql://postgres:postgres@postgres.local:5432/postgres"
    DJANGO_STATIC_ROOT: "/var/www/web/static/"
    ORTHANC1_HOST: "orthanc1.local"
    ORTHANC1_HTTP_PORT: 6501
    ORTHANC1_DICOM_PORT: 7501
    ORTHANC1_DICOMWEB_ROOT: "dicom-web"
    ORTHANC2_HOST: "orthanc2.local"
    ORTHANC2_HTTP_PORT: 6502
    ORTHANC2_DICOM_PORT: 7502
    ORTHANC2_DICOMWEB_ROOT: "dicom-web"
    FILE_TRANSMIT_HOST: "receiver.local"
    FILE_TRANSMIT_PORT: 14638
    STORE_SCP_HOST: "receiver.local"
    STORE_SCP_PORT: 11112

services:
  init:
    <<: *default-app
    hostname: init.local
    volumes:
      - web_data:/var/www/web
      - /mnt:/mnt

  web:
    <<: *default-app
    hostname: web.local
    build:
      context: ..
    volumes:
      - web_data:/var/www/web
      - /mnt:/mnt

  postgres:
    image: postgres:13.13
    hostname: postgres.local
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dicom_worker:
    <<: *default-app
    hostname: dicom_worker.local

  default_worker:
    <<: *default-app
    hostname: default_worker.local

  receiver:
    <<: *default-app
    hostname: receiver.local

  orthanc1:
    image: jodogne/orthanc-plugins:1.12.1
    hostname: orthanc1.local
    configs:
      - source: orthanc1_config
        target: /etc/orthanc/orthanc.json
    volumes:
      - orthanc1_data:/var/lib/orthanc/db

  orthanc2:
    image: jodogne/orthanc-plugins:1.12.1
    hostname: orthanc2.local
    configs:
      - source: orthanc2_config
        target: /etc/orthanc/orthanc.json
    volumes:
      - orthanc2_data:/var/lib/orthanc/db

configs:
  orthanc1_config:
    file: ./orthanc/orthanc1.json
  orthanc2_config:
    file: ./orthanc/orthanc2.json

volumes:
  web_data:
  postgres_data:
  orthanc1_data:
  orthanc2_data:
