version: "3.8"

x-app: &default-app
  restart: always
  image: adit_prod:latest
  env_file:
    - ../.env.prod
  environment:
    ENABLE_REMOTE_DEBUGGING: 0
    DJANGO_SETTINGS_MODULE: "adit.settings.production"
    SSL_CERT_FILE: "/var/www/adit/ssl/cert.pem"
    SSL_KEY_FILE: "/var/www/adit/ssl/key.pem"

services:
  web:
    <<: *default-app
    build:
      target: production
    ports:
      - "80:80"
      - "443:443"
    command: >
      bash -c "
        wait-for-it -s postgres:5432 -t 60 && 
        ./manage.py migrate &&
        ./manage.py collectstatic --no-input &&
        ./manage.py create_admin &&
        ./manage.py generate_cert &&
        daphne -b 0.0.0.0 -p 80 -e ssl:443:privateKey=/var/www/adit/ssl/key.pem:certKey=/var/www/adit/ssl/cert.pem adit.asgi:application
      "
    deploy:
      replicas: 1

  postgres:
    restart: always
    env_file:
      - ../.env.prod
    deploy:
      replicas: 1

  dicom_worker:
    <<: *default-app
    command: ./manage.py dicom_worker
    deploy:
      replicas: 1

  celery_worker:
    <<: *default-app
    command: ./manage.py celery_worker -Q default_queue
    deploy:
      replicas: 1

  celery_beat:
    <<: *default-app
    command: ./manage.py celery_beat
    deploy:
      replicas: 1

  receiver:
    <<: *default-app
    ports:
      - "11112:11112"
    command: ./manage.py receiver
    deploy:
      replicas: 1

  flower:
    <<: *default-app
    deploy:
      replicas: 1

  rabbit:
    restart: always
    deploy:
      replicas: 1

  redis:
    restart: always
    deploy:
      replicas: 1

  orthanc1:
    restart: always
    deploy:
      replicas: 1

  orthanc2:
    restart: always
    deploy:
      replicas: 1
