version: "3.8"

x-app: &default-app
  image: adit_dev:latest
  volumes:
    - ..:/app
  env_file:
    - ./.env.dev
  environment:
    ENABLE_REMOTE_DEBUGGING: 0
    DJANGO_SETTINGS_MODULE: "adit.settings.development"

services:
  web:
    <<: *default-app
    build:
      target: development
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes: # Cave, overwrites the above anchor
      - ..:/app
      - vscode-server:/root/.vscode-server/extensions
      - vscode-server-insiders:/root/.vscode-server-insiders/extensions
    command: >
      bash -c "
        ./scripts/wait-for-it.sh postgres:5432 -t 30 &&
        python ./manage.py reset_orthancs &&
        python ./manage.py migrate &&
        python ./manage.py collectstatic --no-input &&
        python ./manage.py populate_dev_db &&
        python ./manage.py runserver 0.0.0.0:8000
      "

  worker_default:
    <<: *default-app

  worker_dicom_task:
    <<: *default-app

  celery_beat:
    <<: *default-app

  receiver:
    <<: *default-app
    ports:
      - "11122:11112"

  flower:
    <<: *default-app

  postgres:
    environment:
      POSTGRES_PASSWORD: "postgres"

volumes:
  vscode-server:
  vscode-server-insiders:
