x-app: &default-app
  image: adit_dev:latest
  volumes:
    - ..:/app
  env_file:
    - ../.env.dev
  environment:
    ENABLE_REMOTE_DEBUGGING: 0
    DJANGO_SETTINGS_MODULE: "adit.settings.development"
  pull_policy: never # only works with Docker Compose and not Docker Swarm

services:
  init:
    <<: *default-app
    profiles:
      - never

  web:
    <<: *default-app
    build:
      target: development
    ports:
      - "${ADIT_HOST_PORT:-8000}:8000"
      - "${ADIT_DEBUG_PORT:-5678}:5678"
    volumes:
      # Cave, overwrites the above anchor
      - ..:/app
      - vscode-server:/root/.vscode-server/extensions
      - vscode-server-insiders:/root/.vscode-server-insiders/extensions
    command: >
      bash -c "
        wait-for-it -s postgres.local:5432 -t 60 && 
        ./manage.py migrate &&
        ./manage.py collectstatic --no-input &&
        ./manage.py populate_users_and_groups --users 20 --groups 3 &&
        ./manage.py populate_data &&
        ./manage.py runserver 0.0.0.0:8000
      "

  postgres:
    environment:
      POSTGRES_PASSWORD: "postgres"

  dicom_worker:
    <<: *default-app
    command: >
      bash -c "
        wait-for-it -s postgres.local:5432 -t 60 &&
        ./manage.py bg_worker -l debug -q dicom --autoreload
      "

  default_worker:
    <<: *default-app
    command: >
      bash -c "
        wait-for-it -s postgres.local:5432 -t 60 &&
        ./manage.py bg_worker -l debug -q default --autoreload
      "

  receiver:
    <<: *default-app
    ports:
      - "11122:11112"
    command: |
      ./manage.py receiver --autoreload

volumes:
  vscode-server:
  vscode-server-insiders:
