version: "3.8"

x-app: &default-app
  pull_policy: never
  volumes:
    - /mnt:/mnt
  depends_on:
    - postgres
    - rabbit
    - redis
    - orthanc1
    - orthanc2
  environment:
    USE_DOCKER: 1
    DATABASE_URL: "psql://postgres:postgres@postgres:5432/postgres"
    RABBITMQ_URL: "amqp://rabbit"
    REDIS_URL: "redis://redis:6379/0"
    DJANGO_STATIC_ROOT: "/var/www/adit/static/"
    RABBIT_MANAGEMENT_HOST: "rabbit"
    RABBIT_MANAGEMENT_PORT: "15672"
    FLOWER_HOST: "flower"
    FLOWER_PORT: "5555"
    ORTHANC1_HOST: "orthanc1"
    ORTHANC1_HTTP_PORT: 6501
    ORTHANC1_DICOM_PORT: 7501
    ORTHANC2_HOST: "orthanc2"
    ORTHANC2_HTTP_PORT: 6502
    ORTHANC2_DICOM_PORT: 7502

services:
  web:
    <<: *default-app
    build:
      context: ..
    volumes:
      # Cave, overwrites the above anchor
      - /mnt:/mnt
      - adit_data:/var/www/adit

  worker_default:
    <<: *default-app
    command: python manage.py celery_worker -Q default_queue

  worker_dicom_task:
    <<: *default-app
    command: python manage.py celery_worker -Q dicom_task_queue

  celery_beat:
    <<: *default-app
    command: python manage.py celery_beat

  receiver:
    <<: *default-app
    command: python manage.py receiver

  flower:
    <<: *default-app
    expose:
      - "5555"
    command: celery --broker=amqp://rabbit/ flower --url_prefix=flower

  postgres:
    image: postgres:13.1
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # RabbitMQ authentication can't be disabled. So when we try to log into
  # the management console we have to use "guest" as username and password.
  # The real authentication happens by ADIT itself, because the management
  # console is behind a ProxyView.
  rabbit:
    image: rabbitmq:3.8-management
    expose:
      - "5672"
      - "15672"
    volumes:
      - rabbit_data:/var/lib/rabbitmq

  redis:
    image: redis:6.0
    expose:
      - "6379"
    volumes:
      - redis_data:/data

  orthanc1:
    image: jodogne/orthanc-plugins:1.8.1
    expose:
      - "6501"
      - "7501"
    volumes:
      - ./orthanc/orthanc1.json:/etc/orthanc/orthanc.json
      - orthanc1_data:/var/lib/orthanc/db

  orthanc2:
    image: jodogne/orthanc-plugins:1.8.1
    expose:
      - "6502"
      - "7502"
    volumes:
      - ./orthanc/orthanc2.json:/etc/orthanc/orthanc.json
      - orthanc2_data:/var/lib/orthanc/db

volumes:
  adit_data:
  postgres_data:
  rabbit_data:
  redis_data:
  flower_data:
  orthanc1_data:
  orthanc2_data:
